server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  http:
    multipart.max-file-size: 2096KB
    multipart.max-request-size: 2096KB

jwt:
  secret: ndr7jDYV6tUQjyAQj6eUUfh4Q8VeaA
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


